// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TruckNavigator.Infrastructure.Persistence;

#nullable disable

namespace TruckNavigator.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260813181808_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("TruckNavigator.Domain.Trucks.TruckProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("GrossWeightKg")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasTrailer")
                        .HasColumnType("INTEGER");

                    b.Property<double>("HeightMeters")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsSampleData")
                        .HasColumnType("INTEGER");

                    b.Property<double>("LengthMeters")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfAxles")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("TrailerLengthMeters")
                        .HasColumnType("REAL");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<double>("WidthMeters")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("TruckProfiles");
                });
#pragma warning restore 612, 618
        }
    }
}
