// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TruckNavigator.Infrastructure.Persistence;

#nullable disable

namespace TruckNavigator.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("TruckNavigator.Domain.Pois.PointOfInterest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSampleData")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Neighbourhood")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("OpeningHours")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Services")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("SourceRetrievedOn")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("SuitableForHeavyTruck")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("SuitableForLightTruck")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("SuitableForSemiTrailer")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("SuitableForTrailer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VerificationLevel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.ToTable("PointsOfInterest");
                });

            modelBuilder.Entity("TruckNavigator.Domain.Trucks.TruckProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("GrossWeightKg")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasTrailer")
                        .HasColumnType("INTEGER");

                    b.Property<double>("HeightMeters")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsSampleData")
                        .HasColumnType("INTEGER");

                    b.Property<double>("LengthMeters")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfAxles")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("TrailerLengthMeters")
                        .HasColumnType("REAL");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<double>("WidthMeters")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("TruckProfiles");
                });
#pragma warning restore 612, 618
        }
    }
}
